/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package speedclick_marchand_bihr;

/**
 *
 * @author User
 */
public class Fenetre extends javax.swing.JFrame {

    /**
     * Creates new form Fenetre
     */
    private matriceDeBoutons matrice;
    public Fenetre() {
        initComponents();
        GrilleDeBoutons.setVisible(false);
        Timer.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrilleDeBoutons = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Click = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Timer = new javax.swing.JPanel();
        DebutDePartie = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nbLignes = new javax.swing.JTextField();
        nbColonnes = new javax.swing.JTextField();
        Lancer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        GrilleDeBoutons.setBackground(new java.awt.Color(102, 204, 255));
        GrilleDeBoutons.setLayout(new java.awt.GridLayout());

        jButton4.setText("jButton4");
        GrilleDeBoutons.add(jButton4);

        jButton1.setText("jButton1");
        GrilleDeBoutons.add(jButton1);

        Click.setText("clic");
        Click.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClickActionPerformed(evt);
            }
        });
        GrilleDeBoutons.add(Click);

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        GrilleDeBoutons.add(jButton3);

        getContentPane().add(GrilleDeBoutons, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 550, 480));

        Timer.setBackground(new java.awt.Color(255, 204, 153));
        Timer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(Timer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 340, 170));

        DebutDePartie.setBackground(new java.awt.Color(255, 255, 102));
        DebutDePartie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Vous venez de lancez une partie !");
        DebutDePartie.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 260, 40));

        jLabel2.setText("Pour commencer, indiquez :");
        DebutDePartie.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 60, -1, 24));

        jLabel3.setText("-Le nombre de lignes :");
        DebutDePartie.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 96, -1, -1));

        jLabel4.setText("-Le nombre de colonnes:");
        DebutDePartie.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        nbLignes.setText("bj");
        nbLignes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbLignesActionPerformed(evt);
            }
        });
        DebutDePartie.add(nbLignes, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 70, 20));

        nbColonnes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbColonnesActionPerformed(evt);
            }
        });
        DebutDePartie.add(nbColonnes, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 70, 20));

        Lancer.setText("Lancez la partie");
        Lancer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LancerActionPerformed(evt);
            }
        });
        DebutDePartie.add(Lancer, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 130, 30));

        getContentPane().add(DebutDePartie, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 340, 200));

        setBounds(0, 0, 1023, 854);
    }// </editor-fold>//GEN-END:initComponents

    private void ClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClickActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClickActionPerformed

    private void nbColonnesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbColonnesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nbColonnesActionPerformed

    private void LancerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LancerActionPerformed

        GrilleDeBoutons.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_LancerActionPerformed

    private void nbLignesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbLignesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nbLignesActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fenetre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Click;
    private javax.swing.JPanel DebutDePartie;
    private javax.swing.JPanel GrilleDeBoutons;
    private javax.swing.JButton Lancer;
    private javax.swing.JPanel Timer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nbColonnes;
    private javax.swing.JTextField nbLignes;
    // End of variables declaration//GEN-END:variables
}
